### ISSUE TITLE
No response when click Insert File Template

### ISSUE THREAD

**Issue by livrth** [cpinitiative/ide#1]
Hi @cpinitiative this is an excellent project, but it seems there is a small bug, when I click the `Insert File Template` in `File`, the website has no response but  just warns **Reset current file? Any changes you made will be lost.**

![image](https://user-images.githubusercontent.com/45538642/116494083-acc32200-a8d2-11eb-986c-6e9473dffc91.png)

All code in `Main.cpp` has been reset, but I still can't upload my template file.

My broswer edition is **chrome 89.0.4389.114**, then I change to **firefox 88.0**, it also responses nothing.

Maybe it's a feature which is being developed.

As for another suggestion, it would be better if supports display all files in sidebar likes [nerdtree](https://github.com/preservim/nerdtree).

Thanks!

**Comment by thecodingwizard** [comment]
"Insert File Template" might be poorly named -- all it does is resets the file to its default value:

```cpp
// Source: https://usaco.guide/general/io

#include <iostream>
using namespace std;

int main() {
	int a, b, c; cin >> a >> b >> c;
	cout << "sum is " << a+b+c << "\n";
}
```

At the moment, we don't support uploading / setting custom template files (just copy paste the template into the editor), though I think this is a good idea and we may add support for this in the future. We also don't support programs that use multiple files (yet?).

**Comment by livrth** [comment]
> "Insert File Template" might be poorly named -- all it does is reset the file to its default value:
> 
> ```c++
> // Source: https://usaco.guide/general/io
> 
> #include <iostream>
> using namespace std;
> 
> int main() {
> 	int a, b, c; cin >> a >> b >> c;
> 	cout << "sum is " << a+b+c << "\n";
> }
> ```
> 
> At the moment, we don't support uploading / setting custom template files (just copy paste the template into the editor), though I think this is a good idea and we may add support for this in the future. We also don't support programs that use multiple files (yet?).


> "Insert File Template" might be poorly named -- all it does is reset the file to its default value:
> 
> ```c++
> // Source: https://usaco.guide/general/io
> 
> #include <iostream>
> using namespace std;
> 
> int main() {
> 	int a, b, c; cin >> a >> b >> c;
> 	cout << "sum is " << a+b+c << "\n";
> }
> ```
> 
> At the moment, we don't support uploading / setting custom template files (just copy paste the template into the editor), though I think this is a good idea and we may add support for this in the future. We also don't support programs that use multiple files (yet?).

Thanks for 

> "Insert File Template" might be poorly named -- all it does is reset the file to its default value:
> 
> ```c++
> // Source: https://usaco.guide/general/io
> 
> #include <iostream>
> using namespace std;
> 
> int main() {
> 	int a, b, c; cin >> a >> b >> c;
> 	cout << "sum is " << a+b+c << "\n";
> }
> ```
> 
> At the moment, we don't support uploading / setting custom template files (just copy paste the template into the editor), though I think this is a good idea and we may add support for this in the future. We also don't support programs that use multiple files (yet?).

Thanks for the answer.
