### ISSUE TITLE
USACO Problem URLs

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#10]
- [ ] Validate URL (before submit is pressed?)
- [ ] allow pasting of the just the ID (1137)
- [ ] Display the name of the problem somewhere, as well as the input / output format.

<img width="645" alt="Screen Shot 2021-06-20 at 9 41 37 AM" src="https://user-images.githubusercontent.com/21228024/122676345-bdde3000-d1ab-11eb-8922-3ec28156b077.png">

**Comment by thecodingwizard** [comment]
also warn people that linking in-contest problems will not work
