### ISSUE TITLE
Unable to connect to server, connection is always closed

### ISSUE THREAD

**Issue by TinaTabby** [cpinitiative/ide#101]
The connection seems to always be closed. This is also the case for all of the other files I tried. New files also have this issue. Is there something going on? Is the server down?

**Comment by thecodingwizard** [comment]
oops, will fix

**Comment by thecodingwizard** [comment]
should be fixed now, thanks for reporting

**Comment by S-D-Ge** [comment]
Connection still closed all the time for me.

<img width="634" alt="image" src="https://github.com/cpinitiative/ide/assets/52391257/6f7b1e9e-6654-43e0-8a79-db179cef7df8">
