### ISSUE TITLE
Update LSP Installation Instructions

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#106]
https://github.com/cpinitiative/ide#lsp-installation

Step 3: `packages/examples/node` no longer exists

**Comment by thecodingwizard** [comment]
D: I think we should probably bite the bullet and update monaco + the lsp to the latest version.

Relevant files were probably moved here: https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/main/src/server

**Comment by thecodingwizard** [comment]
Our new LSP runs on Modal and is documented in its own repo.
