### ISSUE TITLE
Legacy IDE Connection Closed

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#109]
I get this whenever I open a file. Is this expected?

<img width="1274" alt="Screen Shot 2023-06-13 at 10 44 06 PM" src="https://github.com/cpinitiative/ide/assets/21228024/9e616de2-a3c0-4082-b37c-3ac4fc7e6017">

**Comment by thecodingwizard** [comment]
no 😅

**Comment by danielzsh** [comment]
Oh is this fixed now btw
