### ISSUE TITLE
Playwright Tests Timing Out

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#114]
https://github.com/cpinitiative/ide/actions/runs/5264133371/jobs/10081703239

The latest commit on master was passing before, now it times out when I rerun it. Any clue? @thecodingwizard

**Comment by thecodingwizard** [comment]
Not sure... I'll set a global timeout of 12 minutes so hopefully it uploads an error log we can look at

**Comment by thecodingwizard** [comment]
oh, I think vjudge certificate has expired :////

**Comment by thecodingwizard** [comment]
fixed

**Comment by thecodingwizard** [comment]
I restarted the app with

```
sudo pm2 restart app --cron-restart="0 0 0 1 * *"
```

hopefully this will make it auto-restart once a month which will solve our SSL issues...
