### ISSUE TITLE
Won't take in inputs

### ISSUE THREAD

**Issue by Shubhy-D** [cpinitiative/ide#119]
The IDE won't take in inputs for some reason even after pressing enter multiple times and refreshing.

**Comment by bqi343** [comment]
can you share a link to your code?

**Comment by thecodingwizard** [comment]
I'm not sure if this is your issue, but the IDE does not support taking interactive inputs -- all inputs must be specified in the Inputs tab prior to running your code.

**Comment by Shubhy-D** [comment]
> I'm not sure if this is your issue, but the IDE does not support taking interactive inputs -- all inputs must be specified in the Inputs tab prior to running your code.

Oh okay let me check once more with the input already inside of the inputs tab

**Comment by Shubhy-D** [comment]
Oh it worked! Thank you @thecodingwizard and @bqi343
