### ISSUE TITLE
Missing a Question

### ISSUE THREAD

**Issue by NimeeshS** [cpinitiative/ide#121]
Missing the Cow College Question (http://usaco.org/index.php?page=viewproblem2&cpid=1251)

**Comment by thecodingwizard** [comment]
The search is done through Algolia on the `usacoProblems`

**Comment by thecodingwizard** [comment]
(I assume the issue is referring to the problem search feature within the USACO Guide IDE...)

**Comment by thecodingwizard** [comment]
Fixed by https://github.com/cpinitiative/usaco-guide/pull/4086. Thanks @devo1ution !
