### ISSUE TITLE
Update to clangd-17

### ISSUE THREAD

**Issue by cruelkratos** [cpinitiative/ide#130]
Need an option to toggle error squiggles on and off in editor settings.

**Comment by cruelkratos** [comment]
![IMG_6002](https://github.com/cpinitiative/ide/assets/116339436/80e6f6e0-f3f0-41db-81f0-e1a21f55cc2e)

**Comment by bqi343** [comment]
What’s the error?

**Comment by cruelkratos** [comment]
the code runs  yet an error line is present in the code

**Comment by bqi343** [comment]
Can you share the link to the code?

**Comment by danielzsh** [comment]
> the code runs yet an error line is present in the code as you can see in the image

What's the error message? It could be an issue with discrepancy between intellisense server (`clangd-14`) and the compiler, which I presume is c++17.

**Comment by thecodingwizard** [comment]
yeah, that seems reasonable! I think you're right; we probably need clangd-17. Good catch!

**Comment by danielzsh** [comment]
@cruelkratos this should be fixed, could you test your code again?

**Comment by cruelkratos** [comment]
yep it seems to work now.
