### ISSUE TITLE
Disabling inlay hints

### ISSUE THREAD

**Issue by HansonSin** [cpinitiative/ide#133]
I was solving a problem and when I reloaded the page I saw these little gray boxes in my functions. After some searching I think these are called "inlay hints"? I tried opening a new file in incognito mode but these boxes appeared too. Is there a way to disable it?

![image](https://github.com/cpinitiative/ide/assets/46597093/67f1f133-6733-413b-9375-ecd3b8367f52)

**Comment by HansonSin** [comment]
It may be worth mentioning that it doesn't occur when I open it on mobile.

![Screenshot_20240212_005445](https://github.com/cpinitiative/ide/assets/46597093/725d0b96-167b-44c7-829b-c1cf15e6fe03)

**Comment by thecodingwizard** [comment]
This is a feature for Monaco Editor, which is used on Desktop and not Mobile. To disable such hints, we have to modify Monaco settings: https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorInlayHintsOptions.html

I personally don't like inlay hints either so I'm fine with just disabling these for everyone, but maybe we should consider a better system for letting people customize their editor settings.

**Comment by HansonSin** [comment]
Agree with letting people customize the settings. 😄
