### ISSUE TITLE
Error when connecting to USACO Server

### ISSUE THREAD

**Issue by codecommander03** [cpinitiative/ide#139]
# This is what i get when i submit
![Screenshot from 2024-02-20 18-00-14](https://github.com/cpinitiative/ide/assets/114931868/11dd47ec-9106-4a39-a87a-346485dfa791)

# Console of Firefox
![Screenshot from 2024-02-20 18-00-50](https://github.com/cpinitiative/ide/assets/114931868/2db9a0f8-346e-4ac3-87bd-d1cb787431ea)

# Console of Microsoft Edge
![Screenshot from 2024-02-20 18-14-50](https://github.com/cpinitiative/ide/assets/114931868/b4bee168-a323-4354-9cdd-47cc52bbe25f)

**Comment by thecodingwizard** [comment]
Thanks for reporting this! This seems to be the same issue as #138.
