### ISSUE TITLE
Weird Look on IDE

### ISSUE THREAD

**Issue by zrli28** [cpinitiative/ide#144]
I don't know what happened, but the IDE formatting seems to have been squished, and I don't know how to fix the issue. :/

![Screenshot 2024-04-03 at 10 15 18 PM](https://github.com/cpinitiative/ide/assets/152821436/e1302f2c-dedc-4e22-8bca-89eb4fbe07f2)

**Comment by thecodingwizard** [comment]
If you open in incognito does the issue persist?

**Comment by zrli28** [comment]
I don't use google chrome lol

**Comment by thecodingwizard** [comment]
I can't reproduce this, sorry :(
