### ISSUE TITLE
USACO judge feature stuck

### ISSUE THREAD

**Issue by Shubhy-D** [cpinitiative/ide#145]
The new USACO judge feature seems not to work because everytime that I click submit it never works for any problem and just gets stuck in the loading state.

![image](https://github.com/cpinitiative/ide/assets/81923612/c8559100-b76a-4900-9d59-3365d67ffe6d)

**Comment by thecodingwizard** [comment]
Thanks for reporting this! It is being tracked in #138. Unfortunately, I don't know when (or if) this will be fixed.
