### ISSUE TITLE
i cannot load my project

### ISSUE THREAD

**Issue by Lamaa2024** [cpinitiative/ide#149]
it keeps connecting and connecting

![image](https://github.com/cpinitiative/ide/assets/170168769/07e12ed1-a03a-4343-a4fa-f3d33613bc2d)

**Comment by NotTfueee** [comment]
same issue

**Comment by Pieterkoala** [comment]
Same problem. How can I fix this?

**Comment by Pieterkoala** [comment]
Its fixed! Thanks developers!

**Comment by NotTfueee** [comment]
> Its fixed! Thanks developers!

yep

**Comment by andrewc173** [comment]
same issue
