### ISSUE TITLE
Display Compile Errors / Warnings Next To Corresponding Line

### ISSUE THREAD

**Issue by bqi343** [cpinitiative/ide#3]
Like CSAcademy does:

<img width="376" alt="Screen Shot 2021-05-12 at 3 21 04 PM" src="https://user-images.githubusercontent.com/21228024/118032506-c2eeca80-b335-11eb-8737-ed39982f2174.png">

**Comment by thecodingwizard** [comment]
Is this before or after you hit the run button?

Intellisense / autocomplete / error highlighting is possible with a [language client](https://github.com/TypeFox/monaco-languageclient) but it seems immensely difficult to set up...

**Comment by bqi343** [comment]
after

**Comment by thecodingwizard** [comment]
It's theoretically possible to do it if it's after (just parse the compile error and update monaco). seems extremely hard though :(

**Comment by thecodingwizard** [comment]
#79 will probably accomplish this (though we may need to be careful about flags and stuff)
