### ISSUE TITLE
Request for Zoom / Text-Font Size Increases Feature [ for small laptops display ] 

### ISSUE THREAD

**Issue by dipankarcode** [cpinitiative/ide#37]
In VS Code, there is an option to Zoom Font with [ Mouse Scroll + ctrl ] 
Please add a similar feature to the current text editor, and also for Terminal [ bigger font size option ]  

For Small Laptop [ 13 Inch,  15 inches] it is harder to read the font.

**Comment by bqi343** [comment]
Can't you just adjust your browser zoom settings?
