### ISSUE TITLE
Enable Bracket Pair Colorization 

### ISSUE THREAD

**Issue by Dipankar-Kumar-Singh** [cpinitiative/ide#38]
It is a very important feature especially for the competitive programmer to have bracket pair colorized, as we use a lot of **Nested loops, if-else statements.**

**Comment by bqi343** [comment]
Doesn't seem very important but would be nice to have. Apparently `monaco-editor` doesn't this yet though. (https://github.com/microsoft/monaco-editor/issues/3013)
