### ISSUE TITLE
vjudge SSL certificate expired :(

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/ide#41]
clicking "Open in IDE" on USACO Guide does not work anymore

https://github.com/cpinitiative/usaco-guide/issues/2256

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/3359

**Comment by thecodingwizard** [comment]
Fixed in https://github.com/cpinitiative/vjudge-usaco/commit/3815c23832a8ec97a36838ef6f93304db56dacf9

It actually shouldn't happen again (I think). let me know / reopen this if it does

**Comment by bqi343** [comment]
https://github.com/cpinitiative/usaco-guide/issues/3660

**Comment by thecodingwizard** [comment]
no longer relevant because vjudge doesn't work anymore :(
