### ISSUE TITLE
Cannot read properties of NULL (reading 'addEventListener')

### ISSUE THREAD

**Issue by parth-kabra** [cpinitiative/ide#45]
![image](https://user-images.githubusercontent.com/84372000/143207781-8916b57a-e7a9-4ab1-a13d-4041b3be49c0.png)

Hey, I was exploring USACO IDE when I found this error in the Code. Hope it was helpful ! Also this is my 1st issue :)

Thank You !

**Comment by parth-kabra** [comment]
Sadly I was not able to find the source code on Github Repo

**Comment by thecodingwizard** [comment]
Is it an error in a browser extension?

**Comment by parth-kabra** [comment]
I found this in console in google

**Comment by thecodingwizard** [comment]
Can you provide steps to reproduce this issue? I'm unfortunately unable to see this error on my end. My guess is that it's an error in an browser extension (does this error occur in incognito mode?)
