### ISSUE TITLE
Vim mode doesn't work

### ISSUE THREAD

**Issue by ajxu2** [cpinitiative/ide#55]
When switching from the "Normal" editor mode to the "Vim" editor mode in the "User" tab of Settings, the mode doesn't actually change to Vim; rather, it continues operating like it's in Normal mode. The following message shows up in console when the mode is changed to Vim and "Save" is pressed:

![image](https://user-images.githubusercontent.com/63217938/153322174-c9560087-984d-4c34-8ba2-4640d6eaf4ac.png)

Additionally, if you try to go back to Normal mode after you're in Vim mode, the IDE crashes:

![image](https://user-images.githubusercontent.com/63217938/153322316-32d2159b-2d7c-492d-a977-4f7382cb1f4b.png)

Also, this bug seems to only have appeared about a few days ago, as Vim mode was working fine before then.

**Comment by thecodingwizard** [comment]
thanks for reporting. I think ce7a8a15304e0f42b2ccfab11246c051ddcd651d should fix it. Let me know if you encounter any issues
