### ISSUE TITLE
Copy file button not working

### ISSUE THREAD

**Issue by maggie-j-liu** [cpinitiative/ide#64]
when you haven't added anything to the 3 code editors or the scribble editor, vercel error should explain why

Console:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63619830/159610589-596d53bd-79b2-4422-abcf-7530e3f670b2.png">

From Vercel: 
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/63619830/159610497-d10f8c3b-8a35-445d-bffc-548400f66733.png">

**Comment by thecodingwizard** [comment]
I think 0b33e073f2296ca65db5a169a7bac80702ce4bf9 fixes it
