### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by RmdanJr** [cpinitiative/ide#69]
This error occurs when I press the submit button.
Problem ID: 739
![Screenshot from 2022-06-17 11-08-42](https://user-images.githubusercontent.com/51521033/174267692-0a8139bf-2559-4e88-8f2a-6289bbce16f8.png)

**Comment by hoanganhtu0922** [comment]
i have the same problem =(

**Comment by thecodingwizard** [comment]
should be fixed now, thanks for reporting this issue!
