### ISSUE TITLE
files won't load

### ISSUE THREAD

**Issue by Rexianli** [cpinitiative/ide#81]
All of my files (old files and newly created ones) won't load. The section where the files are meant to be shown displays "Loading files..." and refuses to load despite multiple page refreshes and logging into the account using a different device.
<img width="998" alt="Screen Shot 2022-06-25 at 10 01 53 PM" src="https://user-images.githubusercontent.com/64858789/175796235-6b1f761f-c4e2-4327-9644-e9d6ab31744c.png">

**Comment by sosudo** [comment]
I also had this issue last night. It's fixed now; I can see all of my files. I believe it might've been some server-side problem or it was updating.

**Comment by thecodingwizard** [comment]
I temporarily changed the production deployment. But the code I commented out in this commit https://github.com/cpinitiative/ide/commit/7071a30413b041e908e255725a8e085859f2ae06 should be uncommented...

**Comment by thecodingwizard** [comment]
fixed in f01aec5362bb8c321fe3edf6bd9c45cdb645c376
