### ISSUE TITLE
LSP Server dies due to lack of memory

### ISSUE THREAD

**Issue by thecodingwizard** [cpinitiative/ide#82]
too many people using it at once? :(

**Comment by thecodingwizard** [comment]
temporary workaround: `0 * * * *  kill $(ps -eo etimes,pid,cmd | awk '{if ($3 == "clangd-12" && $1 >= 1500) print $2}')`

processes aren't dying...

**Comment by bqi343** [comment]
Was this resolved?

**Comment by thecodingwizard** [comment]
no... but the workaround sort of works (though it's definitely still possible for the server to crash if a bunch of people use it all at once)

**Comment by thecodingwizard** [comment]
closing in favor of #79
