### ISSUE TITLE
Suggestion: Support custom templates on code files

### ISSUE THREAD

**Issue by Xenophloxic** [cpinitiative/ide#84]
First of all, thank you so much for making usaco.guide, it's the best thing ever!

A quick suggestion for QOL: it would be very helpful if ide.usaco.guide supported custom code templates. For example, a user could add their template to a file and save it so that in the future, they are greeted with that template when they create a new file.

thank you <333

**Comment by bqi343** [comment]
Noted in #33. For now, you can use the "Clone File" button.
