### ISSUE TITLE
Error: An unknown error occurred

### ISSUE THREAD

**Issue by RmdanJr** [cpinitiative/ide#85]
I'm trying to open the problem with id 1203, but it gives me this error.

![image](https://user-images.githubusercontent.com/51521033/188911843-295b0371-8e58-4c11-92bd-116b1012448e.png)

**Comment by bqi343** [comment]
@thecodingwizard do you know what happened?

<img width="934" alt="Screen Shot 2022-09-07 at 11 10 19 AM" src="https://user-images.githubusercontent.com/21228024/188913858-47cee474-7bdf-4d13-9413-7efd47e0c076.png">

**Comment by RmdanJr** [comment]
It seems it doesn't work for all problems!

**Comment by thecodingwizard** [comment]
vjudge certificate expired -- #41 was not fixed :(

**Comment by thecodingwizard** [comment]
fixed by manually restarting server. will become an issue again in ~3 months...
