### ISSUE TITLE
Code Revision History

### ISSUE THREAD

**Issue by AlwaysAcing123** [cpinitiative/ide#90]
Hello, I am solving USACO problems in the USACO Guide IDE, and I find it very annoying when I want to go back to the latest version that got me the most points for that problem. Maybe you could have a place where we could save our code, and then we could access our code from there (aka have a place where it has all our saved codes, and it can show multiple pieces of saved codes depending on how many times we saved the code, and we could also delete one if we wanted to.)

**Comment by bqi343** [comment]
You can download your code or make a copy.

**Comment by thecodingwizard** [comment]
If we ever get around to implementing the YJS rewrite, I think I will try to implement this. It should be quite straightforward with the YJS system
