### ISSUE TITLE
Add Mobile Support

### ISSUE THREAD

**Issue by akhilsharmaa** [cpinitiative/ide#92]
I tried selecting a text in the code by holding the text but can't select it..

Please fix it so it can by use on mobile devices.

**Comment by thecodingwizard** [comment]
We use monaco as our IDE library, and monaco does not have mobile support. We will either need to wait for them to add mobile support (it's been requested for years), or fall back to CodeMirror as needed.

The latter will substantially increase development time, so it will probably only be implemented if a lot of people want to be able to code on their phones.

**Comment by thecodingwizard** [comment]
This is being worked on through CodeMirror: https://github.com/cpinitiative/ide/tree/codemirror
