### ISSUE TITLE
Beta IDE doesn't allow testing manual input after linking to a problem

### ISSUE THREAD

**Issue by Dan4Life** [cpinitiative/ide#99]
When I try running my code from the Input tab, it redirects to the USACO Judge tab and runs on the problem's sample tests instead.
![image](https://user-images.githubusercontent.com/67161460/226665099-b555f346-e191-4004-a58a-e3dc4b6d5e7d.png)

**Comment by thecodingwizard** [comment]
Thanks for reporting this!
